// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idfrnuqhhceyidlxppzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZnJudXFoaGNleWlkbHhwcHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTA2NDQsImV4cCI6MjA3MzA4NjY0NH0.s-Z9Asm_wgXGF8MTOC2JTNZXGaLeCqML0fwsQEy9liI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});